window.fullProductsList = [
    { "id": 1, "title": "Alfajor Havanna Mixto Blanco Y Negro 612g 12 Unidades", "price": "232,28", "category": "Delicatessen", "details": "612g", "image_url": "https://gonzalatin.com/wp-content/uploads/2023/04/Havanna-Alfajor-Mixto-x12.jpg",
        "description": "A autêntica experiência argentina em dose dupla! Esta caixa exclusiva da tradicional marca Havanna traz 12 unidades sortidas dos famosos alfajores Blanco e Negro. Recheados com o inconfundível e farto doce de leite Havanna, as opções vêm cobertas com puro chocolate meio amargo ou um delicado merengue branco. Ideal para presentear, compartilhar em momentos especiais ou simplesmente para saborear o que há de melhor na confeitaria sul-americana. Peso total: 612g."
    },
    { "id": 2, "title": "Chocolate Milka Tender Moments Alpine Milk 405G", "price": "161,50", "category": "Delicatessen", "details": "405G", "image_url": "https://funchal.vtexassets.com/arquivos/ids/209391/foto_1_003.jpg?v=638439979506200000",
        "description": "Momentos de pura suavidade com a qualidade suíça Milka. O Chocolate Milka Tender Moments Alpine Milk (405g) apresenta uma seleção premium de bombons recheados, envoltos no cremoso e clássico chocolate ao leite dos Alpes. A caixa generosa é perfeita para dividir com a família, servir em confraternizações ou presentear quem não resiste ao sabor inconfundível da vaquinha roxa. Uma verdadeira indulgência em cada mordida."
    },
    { "id": 3, "title": "Caramelos Cavendish & Harvey Caramel Drops 130G", "price": "39,50", "category": "Delicatessen", "details": "130G", "image_url": "https://www.candygurus.com/wp-content/uploads/Cavendish-Harry-caramel-box.jpg",
        "description": "Sofisticação em forma de bala. Os Caramelos Cavendish & Harvey Caramel Drops são produzidos na Alemanha com ingredientes selecionados, entregando uma experiência única de sabor. O exterior de caramelo rico e amanteigado esconde um coração surpreendente de puro chocolate derretido. Acondicionadas na clássica e elegante lata dourada de 130g, estas balas são ideais para ter sempre por perto, seja no carro, no escritório ou em casa."
    },
    { "id": 4, "title": "Chocolate Swiss Dream 100G", "price": "84,82", "category": "Delicatessen", "details": "100G", "image_url": "https://k21market.com/wp-content/uploads/2025/04/CHOCOLATE-SWISS-DREAM-BARRA-MILK-NUTS-CHOCOLATE-100G.jpg",
        "description": "Um convite para saborear a verdadeira tradição suíça. O Chocolate Swiss Dream (100g) é elaborado com cacau de alta qualidade e o inigualável leite dos Alpes Suíços, resultando em uma barra de textura aveludada e derretimento perfeito na boca. Uma escolha clássica e requintada para os paladares mais exigentes que buscam a essência do chocolate europeu em sua forma mais pura."
    },
    { "id": 5, "title": "Chocolate Brookside Dark Açai & Blueberry 198G", "price": "98,76", "category": "Delicatessen", "details": "198G", "image_url": "https://http2.mlstatic.com/D_NQ_NP_872524-MLB75442786408_042024-O.webp",
        "description": "A combinação perfeita entre o exótico e o sofisticado. O Chocolate Brookside traz um interior macio e frutado com os sabores intensos e antioxidantes do açaí e do mirtilo (blueberry), generosamente envoltos por uma camada de chocolate amargo premium. Uma opção deliciosa e equilibrada para quem busca um snack diferenciado, unindo notas frutadas e a intensidade do cacau em um pacote prático de 198g."
    },
    { "id": 6, "title": "Chocolate Pistaccio Royale 200g", "price": "174,28", "category": "Delicatessen", "details": "200g", "image_url": "https://media.istockphoto.com/id/1069805080/photo/chocolate-pistaccio-cake-with-christmas-decoration.webp?b=1&amp;s=170667a&amp;w=0&amp;k=20&amp;c=RA_NokYPca8ccc-iSAqTAAAQ3n0ZQnZHpUXkwdv5_Xs=",
        "description": "Uma obra-prima para os amantes de nozes nobres. O Chocolate Pistaccio Royale (200g) une a cremosidade de um chocolate de excelente qualidade à textura crocante e ao sabor inconfundível dos melhores pistaches. Cada pedaço revela uma generosa quantidade de pistaches inteiros ou em pedaços, proporcionando um contraste perfeito e uma experiência de degustação verdadeiramente real e indulgente."
    },
    { "id": 7, "title": "Chocolate Milka Assorted Travel Collection - 340g", "price": "174,28", "category": "Delicatessen", "details": "340g", "image_url": "https://i.pinimg.com/originals/80/fb/bb/80fbbba383d7554c56acde5dda6ec19c.png",
        "description": "Uma viagem pelos melhores sabores da Milka sem sair de casa. A edição exclusiva Travel Collection (340g) reúne uma seleção dos bombons e miniaturas mais adorados da marca suíça, todos elaborados com o autêntico leite dos Alpes. Com diversas opções de recheios e texturas em uma única embalagem, é a escolha ideal para descobrir novos favoritos, presentear apaixonados por chocolate ou adoçar qualquer momento do dia."
    },
    { "id": 8, "title": "Chocolate Guylian Original Seashell 250G", "price": "145,20", "category": "Delicatessen", "details": "250G", "image_url": "https://m.media-amazon.com/images/I/71LF3demJzL._AC_SL1500_.jpg",
        "description": "A mundialmente famosa obra de arte em chocolate belga. Os icônicos frutos do mar da Guylian (Original Seashells - 250g) são meticulosamente esculpidos e mesclam os chocolates branco, ao leite e amargo. O grande segredo está no seu interior: um recheio praliné de avelã incrivelmente cremoso e rico, torrado segundo a receita tradicional da marca. Um presente sofisticado e inesquecível."
    },
    { "id": 9, "title": "Chocolate Guylian Temptations Mix 522 Gr", "price": "278,74", "category": "Delicatessen", "details": "522 Gr", "image_url": "https://www.apolonia.com/fotos/produtos/13/1348701_01_09-11-2023_g.jpg",
        "description": "A máxima expressão da confeitaria belga em uma caixa sortida e abundante. O Guylian Temptations Mix (522g) oferece uma seleção generosa dos melhores bombons recheados da marca, no icônico formato de cavalo-marinho. Cada embalagem individual guarda sabores distintos e surpreendentes, desde o clássico praliné até caramelo e trufas, garantindo uma experiência de degustação premium para toda a família ou para impressionar convidados."
    },
    { "id": 10, "title": "Chocolate Hersheys Choco Milk Dippretzelpch 241GR", "price": "104,57", "category": "Delicatessen", "details": "241GR", "image_url": "https://www.cvs.com/bizcontent/merchandising/productimages/high_res/34000214648.jpg",
        "description": "O contraste perfeito entre o doce e o salgado, o crocante e o cremoso. Os tradicionais pretzels assados ganham uma cobertura generosa do clássico chocolate ao leite Hershey's. O pacote de 241g de Hershey's Dipped Pretzels é o snack definitivo para maratonas de séries, encontros com amigos ou para matar aquela vontade de um doce com um toque de sal marinho. Irresistível a cada mordida."
    },
    { "id": 11, "title": "Chtoura Dulce Garden Halawa Tradicional 400GR", "price": "58,09", "category": "Delicatessen", "details": "400GR", "image_url": "https://zonasul.vtexassets.com/arquivos/ids/3144735/VF4qT-qqCUAAAAAAAAUilg.jpg?v=638314667153300000",
        "description": "Viaje pelos sabores do Oriente Médio com o tradicional Halawa Chtoura Dulce Garden. Este doce clássico, feito à base de pasta de gergelim (tahine) e açúcar, possui uma textura única, que se desfaz na boca, e um sabor profundo e reconfortante de nozes. Em uma embalagem de 400g, é perfeito para ser saboreado puro, acompanhado de um chá ou café forte, ou utilizado em receitas de sobremesas criativas."
    },
    { "id": 12, "title": "Chtoura Dulce Garden Halawa Whit Chocolate 400GR", "price": "58,09", "category": "Delicatessen", "details": "400GR", "image_url": "https://chtouraroyal.com/wp-content/uploads/2020/11/Chtoura-Garden-Halawa-with-Chocolate-Lebanon-12-400g--1152x1536.jpg",
        "description": "A tradição árabe encontra o toque moderno do chocolate. O Halawa Chtoura Dulce Garden com Chocolate (400g) traz a clássica massa de gergelim (tahine) que derrete na boca, enriquecida com deliciosas notas de cacau. Uma combinação de texturas e sabores que eleva esta iguaria do Oriente Médio, tornando-a ainda mais atraente para os amantes de doces e uma sobremesa exótica para surpreender."
    },
    { "id": 13, "title": "Chocolate Milka Moments Assorted 169g", "price": "82,04", "category": "Delicatessen", "details": "169g", "image_url": "https://down-br.img.susercontent.com/file/sg-11134201-7qvfy-lgwvxckgwi2o77" },
    { "id": 14, "title": "Chocolate Milka Alpine Milk 270g", "price": "98,76", "category": "Delicatessen", "details": "270g", "image_url": "https://hortifrutibr.vtexassets.com/arquivos/ids/157884/Chocolate-Milka-Alpine-Milk-100G.jpg?v=638671093219900000" },
    { "id": 15, "title": "Chocolate Milka Nussini 31.5g 5 Unidades", "price": "84,82", "category": "Delicatessen", "details": "31.5g", "image_url": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m6sfvc9uur003a" },
    { "id": 16, "title": "Chocolate After Eight Strawberry & Mint 200g", "price": "114,33", "category": "Delicatessen", "details": "200g", "image_url": "https://cdn.dooca.store/239/products/ixdcfkfif7qkfaasit6t60agqt6v29inch78_640x640+fill_ffffff.jpg?v=1668511826&amp;webp=0" },
    { "id": 17, "title": "Chocolate Kit Kat White Assorted 400g", "price": "143,15", "category": "Delicatessen", "details": "400g", "image_url": "https://drogariavenancio.vtexassets.com/arquivos/ids/1094334/68594_2.jpg?v=638385847799900000" },
    { "id": 18, "title": "Alfajor Havanna Mixto Edição Aniversário 70 Anos 612g", "price": "232,28", "category": "Delicatessen", "details": "612g", "image_url": "https://sejafranqueado.havanna.com.br/wp-content/uploads/elementor/thumbs/Imagem-2-qi48jv0acbv75pqzd032nmvesx8wfxceyomknkuq28.jpg" },
    { "id": 19, "title": "Alfajor Havanna Chocolate 612g 12 Unidades", "price": "232,28", "category": "Delicatessen", "details": "612g", "image_url": "https://nissei.com/media/catalog/product/cache/24e3af3791642c18c52611620aeb2e21/1/2/12_3_1.jpg" },
    { "id": 20, "title": "Caramelos Cavendish & Harvey Pear Drops 175G", "price": "34,06", "category": "Delicatessen", "details": "175G", "image_url": "https://kennedyspharmacy.com.au/wp-content/uploads/2023/11/Cavendish-Harvey-Pear-Blackberry-Drops-768x616.jpg",
        "description": "O sabor da infância com um toque de elegância europeia. As balas Cavendish & Harvey Creamy Butterscotch são elaboradas com manteiga de alta qualidade e caramelo, resultando em gotas douradas de sabor rico, cremoso e profundamente reconfortante. Apresentadas na clássica lata metálica dourada de 175g, são perfeitas para presentear ou para apreciar lentamente a qualquer hora do dia."
    },
    { "id": 21, "title": "Chocolate Milka & Oreo 300g", "price": "114,33", "category": "Delicatessen", "details": "300g", "image_url": "https://naturalterra.vtexassets.com/arquivos/ids/157638/Chocolate-Milka-Oreo-100G.jpg?v=638671093212830000" },
    { "id": 22, "title": "Chocolate Milka Mmmax Peanut Caramel 276g", "price": "114,33", "category": "Delicatessen", "details": "276g", "image_url": "https://domolivio.vtexassets.com/arquivos/ids/541667/Chocolate-Peanut-Caramel-Milka-276g.jpg?v=638683372962670000" },
    { "id": 23, "title": "Gaseosa Dr Pepper 355 ML", "price": "13,85", "category": "Delicatessen", "details": "355 ML", "image_url": "https://fenix.kip.sv/wp-content/uploads/products/gaseosa-de-dieta-dr-pepper-178372-1.png" },
    { "id": 24, "title": "Chocolate Nestle L'Atelier Almonds & Hazelnuts 170g", "price": "114,33", "category": "Delicatessen", "details": "170g", "image_url": "https://www.mustakshif.com/public/uploads/products/nestle-nestle-latelier-dark-chocolate-blueberry-almonds-hazelnuts-100-g_7613037985085_Mustakshif.png" },
    { "id": 25, "title": "Mermelada Seasonal Assorted Fruit Jam 227g", "price": "34,45", "category": "Delicatessen", "details": "227g", "image_url": "https://fitfruitstore.com/wp-content/uploads/2022/12/Mermelada-Artesanal-Gourmet-Tomate-FITFRUIT.jpeg" },
    { "id": 26, "title": "Mermelada Seasonal Raspberry No Sugar 227g", "price": "34,45", "category": "Delicatessen", "details": "227g", "image_url": "http://www.ujarras.com/wp-content/uploads/2014/10/Mermelada-de-piña-SUGAR-FREE.jpg" },
    { "id": 27, "title": "Caramelos Cavendish & Harvey Mango Drops 200g", "price": "73,18", "category": "Delicatessen", "details": "200g", "image_url": "https://wealzin.com.bd/wp-content/uploads/2023/05/Cavendish-Harvey-Mango-Kiwi-Drops-200g.jpg" },
    { "id": 28, "title": "Caramelos Cavendish & Harvey Mixed Fruit 200g", "price": "60,67", "category": "Delicatessen", "details": "200g", "image_url": "https://www.cottagedelight.co.uk/wp-content/uploads/2023/05/67.png" },
    { "id": 29, "title": "Caramelos Cavendish & Harvey Mixed Fruit 966g", "price": "170,05", "category": "Delicatessen", "details": "966g", "image_url": "https://images.tcdn.com.br/img/img_prod/584699/balas_mixed_fruit_selection_cavendish_e_harvey_966g_2767_1_20191022120425.jpeg" },
    { "id": 30, "title": "Caramelos Cavendish & Harvey Sour Cherry 200g", "price": "41,01", "category": "Delicatessen", "details": "200g", "image_url": "https://images.tcdn.com.br/img/img_prod/584699/180_balas_sour_cherry_drops_cavendish_e_harvey_200g_2947_1_20191125161901.jpeg",
        "description": "O encontro entre a doçura do caramelo e a acidez refrescante da cereja. As balas alemãs Cavendish & Harvey Sour Cherry Drops (200g) oferecem uma explosão frutada no paladar, feitas com suco de fruta real e ingredientes cuidadosamente selecionados. A lata dourada clássica preserva o frescor destas pedras preciosas de açúcar, tornando-as um mimo elegante para ter sempre à mão."
    },
    { "id": 31, "title": "Gaseosa Ginger Ale 355 ML", "price": "13,85", "category": "Delicatessen", "details": "355 ML", "image_url": "https://spidregpe.vteximg.com.br/arquivos/ids/1136753-1000-1000/Gaseosa-Canada-Dry-Ginger-Ale-Lata-355-ml-1-307927.jpg?v=638247025001870000" },
    { "id": 32, "title": "Aceite De Oliva Olivas De Neuquen 500 Ml", "price": "143,15", "category": "Delicatessen", "details": "500 Ml", "image_url": "https://spidregpe.vteximg.com.br/arquivos/ids/726676-1000-1000/CCOMPESPIDXUC392IA34ZI-1-1.jpg?v=637869217090300000" },
    { "id": 33, "title": "Alfajor Havanna Mixto 306g 6 Unidades", "price": "114,33", "category": "Delicatessen", "details": "306g", "image_url": "https://santaluzia.vteximg.com.br/arquivos/ids/962851-740-515/1036076.jpg?v=637384822909100000" },
    { "id": 34, "title": "Chocolate Milka Alpine Milk 100g", "price": "34,45", "category": "Delicatessen", "details": "100g", "image_url": "https://naturalterra.vtexassets.com/arquivos/ids/157884/Chocolate-Milka-Alpine-Milk-100G.jpg?v=638671093219900000" },
    { "id": 35, "title": "Chocolate Milka Choco Wafer 150g", "price": "73,18", "category": "Delicatessen", "details": "150g", "image_url": "https://emporiohungaro.com.br/wp-content/uploads/2020/05/milka_wafer.jpg" },
    { "id": 36, "title": "Caramelos Cavendish & Harvey Wild Berry 175G", "price": "34,06", "category": "Delicatessen", "details": "175G", "image_url": "https://mambodelivery.vtexassets.com/arquivos/ids/186220/bala-wild-berry-cavendish-harvey-175g.jpg?v=637959237947630000",
        "description": "O sabor intenso dos bosques europeus em cada bala. As Wild Berry Drops da Cavendish & Harvey (175g) capturam a essência de amoras, mirtilos e framboesas em caramelos duros que derretem lentamente na boca. Polvilhadas com açúcar de confeiteiro para não grudarem e apresentadas em uma charmosa lata selada, são a escolha certa para amantes de frutas vermelhas."
    },
    { "id": 37, "title": "Mantequilla De Mani Jif Creamy 454g", "price": "98,76", "category": "Delicatessen", "details": "454g", "image_url": "https://www.flavers.pt/wp-content/uploads/2018/02/Jif-Peanut-Butter-Creamy-454g.png" },
    { "id": 38, "title": "Mantequilla De Mani Jif Crunchy 454g", "price": "98,76", "category": "Delicatessen", "details": "454g", "image_url": "https://www.flavers.pt/wp-content/uploads/2020/07/Jif-Peanut-Butter-Crunchy-454g.jpg" },
    { "id": 39, "title": "Chocolate Ferrero Rocher Christmas T30 375g", "price": "184,17", "category": "Delicatessen", "details": "375g", "image_url": "https://imgprd.martinsatacado.com.br/catalogoimg/97107/01_97107_01.jpg?v=050420242148;ims=1000x" },
    { "id": 40, "title": "Galletas Lotus Biscoff 250g", "price": "51,92", "category": "Delicatessen", "details": "250g", "image_url": "https://www.secondmedic.com/app/asset/site_images/newproduct/WellnessForever202211181100394.webp" },
    { "id": 41, "title": "Chocolate Milka Oreo 100g", "price": "34,45", "category": "Delicatessen", "details": "100g", "image_url": "https://naturalterra.vtexassets.com/arquivos/ids/160756/Chocolate-Milka-Oreo-100G.jpg?v=638671093511230000" },
    { "id": 42, "title": "Bebida Energizante Red Bull 250 Ml", "price": "13,85", "category": "Delicatessen", "details": "250 Ml", "image_url": "https://spidregpe.vteximg.com.br/arquivos/ids/1137351-1000-1000/frontal-4827.jpg?v=638247598610630000" },
    { "id": 43, "title": "Caramelos Cavendish & Harvey Cherry With Lime 175G", "price": "39,50", "category": "Delicatessen", "details": "175G", "image_url": "https://www.brooksales.co.za/wp-content/uploads/2021/09/cavendish-harvey-double-fruit-cherry-with-lime-filling.jpg",
        "description": "Uma combinação ousada e irresistível. O sabor profundo e doce da cereja é elevado pelo toque cítrico e brilhante do limão taiti nas balas Cavendish & Harvey Cherry with Lime (175g). A qualidade superior dos ingredientes garante um sabor autêntico de fruta do início ao fim. Uma bala premium para refrescar e adoçar o seu dia com sofisticação."
    },
    { "id": 44, "title": "Caramelos Cavendish & Harvey Blackcurrant Apple 175g", "price": "45,31", "category": "Delicatessen", "details": "175g", "image_url": "https://www.eastereggwarehouse.com.au/wp-content/uploads/2025/05/Cavendish-and-Harvey-duo-Blackcurrant-with-Apple-filling-175g.jpg",
        "description": "Uma surpresa líquida a cada bala. Diferente das versões tradicionais, a Cavendish & Harvey Blackcurrant with Apple Filling (175g) apresenta uma casca externa de caramelo duro sabor groselha negra e esconde um centro deliciosamente macio e recheado com um refrescante purê de maçã verde. Um jogo de texturas e sabores europeus verdadeiramente inesquecível."
    },
    { "id": 45, "title": "Doce Turco Lokma's Lokum Avelã Caixa 300G", "price": "81,33", "category": "Delicatessen", "details": "300G", "image_url": "https://2.bp.blogspot.com/-CGlV66KDre8/WdVIr-3eiAI/AAAAAAAAPZw/naSnsVfZI54EuJ04K-3gzIgIBPMDHyxagCLcBGAs/s1600/DSC00081.JPG",
        "description": "O clássico Manjar Turco elevado à potência máxima de crocância. O Lokum de Avelã da Lokma's (300g) apresenta a tradicional massa macia e adocicada, ricamente pontilhada com avelãs inteiras torradas. O contraste entre a goma suave que derrete na boca e o craquelar das nozes nobres proporciona uma experiência degustativa rica, digna das tradições milenares do Oriente."
    },
    { "id": 46, "title": "Doce Turco Lokma's Sultan Sarmasi Frutas 300G", "price": "63,90", "category": "Delicatessen", "details": "300G", "image_url": "https://lezzetci.com/wp-content/uploads/2022/08/sultan-sarmasi-lokum-tarifi.jpg",
        "description": "A indulgência oriental encontra a paixão ocidental. Os rolinhos Sultan Sarmasi da Lokma's (300g) combinam a textura elástica e suave do manjar turco com um coração macio de chocolate premium, tudo isso abraçado por uma generosa cobertura de flocos de coco. Uma sobremesa exótica e decadente que promete surpreender o paladar e embelezar a mesa."
    },
    { "id": 47, "title": "Doce Turco Lokma's Sultan Chocolate Coco 300G", "price": "63,90", "category": "Delicatessen", "details": "300G", "image_url": "https://turkishalibazaar.com/wp-content/uploads/2023/12/kakaolu-sultan-lokum-kg-952-11-B.png" },
    { "id": 48, "title": "Doce Turco Lokma's Meyvelikus Frutas 300G", "price": "63,90", "category": "Delicatessen", "details": "300G", "image_url": "https://www.acidadeon.com/tudoep/wp-content/uploads/sites/10/2023/12/doce_lokum_1200x675_01062023092902-1024x576.jpg",
        "description": "A essência dos pomares concentrada em cubos de puro deleite. O Lokum Meyvelikus da Lokma's (300g) é a versão festiva e sortida do manjar turco, trazendo uma seleção de sabores frutados variados. Com sua clássica textura que se desfaz suavemente e polvilhado de açúcar, é uma guloseima leve, alegre e perfeita para degustar lentamente em boa companhia."
    },
    { "id": 49, "title": "Doce Turco Lokma's Lokum Coco Pistache 300G", "price": "63,90", "category": "Delicatessen", "details": "300G", "image_url": "https://http2.mlstatic.com/D_NQ_NP_696782-MLB81578193013_122024-O.webp",
        "description": "O casamento perfeito dos sabores do Oriente Médio. O Lokma's Lokum de Coco e Pistache (300g) é uma verdadeira joia da confeitaria turca. A massa tenra é enriquecida com o inconfundível sabor e o verde vibrante do pistache torrado, finalizada com uma generosa camada de coco ralado. Um doce refinado, crocante e aromático, ideal para ocasiões especiais."
    },
    { "id": 50, "title": "Chocolate Kinder Rich In Milk Mini 460G", "price": "145,20", "category": "Delicatessen", "details": "460G", "image_url": "https://cellshop.com/media/catalog/product/1/5/1545760_1_1.jpg?optimize=medium&amp;bg-color=255,255,255&amp;fit=bounds&amp;height=616&amp;width=616&amp;canvas=616:616",
        "description": "O sabor inconfundível que as crianças amam e os adultos não resistem, agora em um formato super prático. O pacote Kinder Mini (460g) vem recheado de barrinhas individuais que trazem o clássico e delicioso chocolate ao leite e o farto recheio cremoso rico em leite. Um pacote tamanho família perfeito para lancheiras, festinhas ou para ter sempre um docinho porcionado em casa."
    },
    { "id": 51, "title": "Doce Turco Lokma's Lokum Baunilha 300G", "price": "63,90", "category": "Delicatessen", "details": "300G", "image_url": "https://2.bp.blogspot.com/-CGlV66KDre8/WdVIr-3eiAI/AAAAAAAAPZw/naSnsVfZI54EuJ04K-3gzIgIBPMDHyxagCLcBGAs/s1600/DSC00081.JPG",
        "description": "A elegância da simplicidade na confeitaria oriental. O Lokum de Baunilha da Lokma's (300g) traz o autêntico e milenar Manjar Turco em sua forma mais delicada. Com uma textura incrivelmente macia que se desfaz na boca, o toque suave e aromático da baunilha torna este doce a companhia perfeita para equilibrar o paladar após um café expresso forte ou um chá escuro."
    },
    { "id": 52, "title": "Biscoito Danisa Tradicional Butter Cookies - 908GR", "price": "124,33", "category": "Delicatessen", "details": "908GR", "image_url": "https://amoradistribuidora.com.br/wp-content/uploads/2024/11/532122dc0553c78574f34abee36e0657.jpeg",
        "description": "Excelência em tamanho ideal para presentear. A clássica lata de 454g dos Biscoitos Danisa Tradicionais oferece a autêntica receita de \"butter cookies\" dinamarqueses. Com ingredientes selecionados e muita manteiga, as formas sortidas garantem um espetáculo visual e gustativo para a hora do café ou do chá. Uma escolha de bom gosto que nunca sai de moda."
    },
    { "id": 53, "title": "Chocolate Goldkenn Rémy Martin Cognac 100G", "price": "84,82", "category": "Delicatessen", "details": "100G", "image_url": "https://http2.mlstatic.com/D_NQ_NP_721290-MLB74174214825_012024-O.webp",
        "description": "O ápice da sofisticação em uma barra de chocolate. A confeitaria suíça premium da Goldkenn uniu forças com a destilaria francesa Rémy Martin para criar esta obra-prima de 100g. Cada quadrado de puro chocolate ao leite esconde um coração líquido do luxuoso Cognac Fine Champagne. Uma experiência de degustação madura, intensa e inesquecível para paladares exigentes."
    },
    { "id": 54, "title": "Chocolate Goldkenn Licor Amarula 100G", "price": "84,82", "category": "Delicatessen", "details": "100G", "image_url": "https://divvino.vtexassets.com/arquivos/ids/158618/4951571.png?v=638362798902800000",
        "description": "A magia da savana africana abraçada pelo melhor chocolate suíço. Esta barra premium da Goldkenn (100g) é recheada com o autêntico e cremoso licor de Amarula, extraído da exótica fruta Marula. O contraste entre o chocolate ao leite que derrete suavemente e o recheio licoroso e aveludado proporciona um momento de puro prazer e indulgência."
    },
    { "id": 55, "title": "Chocolate Goldkenn Jack Daniel's 100G", "price": "84,82", "category": "Delicatessen", "details": "100G", "image_url": "https://down-br.img.susercontent.com/file/br-11134207-7r98s-llc0jqrffaxid9",
        "description": "A atitude do Tennessee em formato de chocolate premium. Para os amantes de um bom whiskey, a barra Goldkenn Jack Daniel's (100g) traz o contraste perfeito entre a suavidade do mais fino chocolate ao leite suíço e o caráter marcante do famoso whiskey americano. Cada pedaço rompe para revelar um xarope líquido autêntico de Jack Daniel's. Um presente ousado e cheio de personalidade."
    },
    { "id": 56, "title": "Biscoito Ferrero Nutella Biscuits 276G", "price": "73,18", "category": "Delicatessen", "details": "276G", "image_url": "https://supernossoio.vtexassets.com/arquivos/ids/264170/220165.jpg?v=638272653735870000",
        "description": "O lanche que conquistou o mundo. Os Nutella Biscuits (276g) trazem um biscoito dourado, assado até atingir a crocância perfeita, e generosamente recheado com o inconfundível creme de avelã com cacau da Ferrero. O prático pacote resselável mantém o frescor e a textura por muito mais tempo, sendo a pedida certa para matar a vontade de doce a qualquer hora do dia."
    },
    { "id": 57, "title": "Bolacha Gangfu Macaron Caixa 50G", "price": "34,45", "category": "Delicatessen", "details": "50G", "image_url": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgasv3xl3u2s68",
        "description": "Uma releitura asiática delicada e surpreendente. As Bolachas Gangfu Macaron (50g) oferecem uma experiência leve e crocante, inspirada no clássico doce francês, mas com a precisão dos snacks orientais. Embaladas em uma charmosa caixa, são ideais para acompanhar chás claros, decorar mesas de doces ou simplesmente desfrutar de um mimo suave no meio da tarde."
    },
    // VINHOS / BEBIDAS
    { "id": 58, "title": "Vinho Herederos del Marqués de Riscal XR 750ml", "price": "373,05", "category": "Bebidas", "details": "750ml", "image_url": "https://cellshop.com/media/catalog/product/4/8/4801788_1_48f7_1.jpg?optimize=medium&amp;bg-color=255,255,255&amp;fit=bounds&amp;height=265&amp;width=265&amp;canvas=265:265",
        "description": "Uma homenagem aos grandes mestres adegueiros de Rioja. O Marqués de Riscal XR (750ml) faz referência aos barris de \"Extra Reserva\", selecionados a dedo por sua qualidade superior. Elaborado principalmente com Tempranillo, é um tinto complexo, com aromas de frutas negras maduras, alcaçuz, canela e pimenta. Seus taninos maduros e final persistente pedem carnes grelhadas e pratos robustos."
    },
    { "id": 59, "title": "Vinho Quinta do Vallado Porto Tawny 10 Anos - 500mL", "price": "540,86", "category": "Bebidas", "details": "500mL", "image_url": "https://d2r9epyceweg5n.cloudfront.net/stores/058/829/products/vinho-do-porto-quinta-do-vallado-10-anos1-5db1c609bfaf33b85d15121935795951-640-0.jpg",
        "description": "A elegância do tempo lapidando o Douro. O Vallado Tawny 10 Anos (500ml) é um vinho do Porto excepcional, envelhecido em velhas pipas de carvalho. Apresenta uma sedutora cor acobreada e exala aromas ricos de frutos secos (nozes, avelãs), praliné, casca de laranja confitada e tabaco. Na boca, é aveludado e interminável. Apresentado em uma garrafa elegante, é o rei das sobremesas."
    },
    { "id": 60, "title": "Vinho Graham's Fine Tawny Port 750ml", "price": "244,41", "category": "Bebidas", "details": "750ml", "image_url": "https://ciadovinho.cdn.magazord.com.br/img/2024/12/produto/6841/488.jpg",
        "description": "O equilíbrio perfeito entre a fruta jovem e a sabedoria da madeira. O Graham's Fine Tawny (750ml) é um Porto clássico, envelhecido em tonéis de carvalho que lhe conferem uma cor âmbar e suavizam seus taninos. Revela aromas deliciosos de caramelo, passas e um toque de baunilha. Mais leve que um Ruby, é um excelente Porto para o dia a dia, acompanhando tartes de frutas e sobremesas de caramelo."
    },
    { "id": 61, "title": "Vinho Graham's Six Grapes Reserve Port 750ml", "price": "373,46", "category": "Bebidas", "details": "750ml", "image_url": "https://cellshop.com/media/catalog/product/3/2/3237236_1_1.jpg?optimize=medium&amp;bg-color=255,255,255&amp;fit=bounds&amp;height=616&amp;width=616&amp;canvas=616:616",
        "description": "O \"Vintage para todos os dias\". O lendário Graham's Six Grapes (750ml) é um Porto Ruby Reserve icônico, feito com as mesmas uvas que compõem os cobiçados Vinhos do Porto Vintage da marca. Encorpado, vigoroso e de um vermelho escuro profundo, transborda notas de amoras, cerejas negras e chocolate. Maravilhoso para harmonizar com queijos curados e sobremesas intensas de chocolate."
    },
    { "id": 62, "title": "Vinho Quinta do Vallado Touriga Nacional 2019 750ml", "price": "445,25", "category": "Bebidas", "details": "750ml", "image_url": "https://tfdbat.vtexassets.com/arquivos/ids/5510012/92363_1.jpg?v=638212193557730000",
        "description": "A uva rainha de Portugal no seu esplendor absoluto. O Quinta do Vallado Touriga Nacional (750ml) é um tinto do Douro que exibe uma exuberância aromática impressionante, com as inconfundíveis notas florais de violeta e bergamota, mescladas com frutos do bosque e especiarias. Encorpado, com taninos finos e um final longo e fresco. Um parceiro luxuoso para carnes assadas e pratos de caça."
    },
    { "id": 63, "title": "Vinho Conde de Serpa Grande Reserva 2015 750ml", "price": "540,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.comprasparaguai.com.br/media/fotos/produtos/thumbs/big/c1be1ee266a3e2945f6e9457f6a0a16429f38804.jpg",
        "description": "A alma do Alentejo engarrafada com classe e maturidade. O Conde de Serpa Grande Reserva 2015 (750ml) é um tinto português que atingiu um belo ponto de evolução. Apresenta um nariz complexo de frutas negras em compota, cacau, notas terrosas e toques balsâmicos. Na boca, revela-se volumoso, com taninos macios e perfeitamente integrados. Ideal para acompanhar pratos tradicionais como cordeiro assado e ensopados."
    },
    { "id": 64, "title": "Vinho M. Chapoutier Les Granilites 2020 750ml", "price": "540,86", "category": "Bebidas", "details": "750ml", "image_url": "https://http2.mlstatic.com/D_NQ_NP_687292-MLB53304400267_012023-O.webp",
        "description": "A pureza mineral do norte do Vale do Rhône. O Les Granilites (750ml) é um Syrah espetacular, proveniente de solos graníticos íngremes. Essa origem confere ao vinho uma tensão e frescor únicos. Desperta os sentidos com notas de frutas vermelhas crocantes, pimenta preta esmagada e grafite. No paladar é preciso, elegante e estruturado. Uma escolha refinada para paladares que buscam vinhos de terroir."
    },
    { "id": 65, "title": "Vinho M. Chapoutier Deschants 2021 750ml", "price": "540,86", "category": "Bebidas", "details": "750ml", "image_url": "https://http2.mlstatic.com/D_NQ_NP_687292-MLB53304400267_012023-O.webp" },
    { "id": 66, "title": "Vinho M. Chapoutier Les Jocasses 2021 750ml", "price": "540,86", "category": "Bebidas", "details": "750ml", "image_url": "https://res.cloudinary.com/evino/image/upload/t_bottle_mid,f_auto/v1/products/1000005485-standing-front.jpg",
        "description": "Potência e calor do sul da França. O Les Jocasses Gigondas (750ml) é um tinto robusto dominado pela uva Grenache. Reflete o clima ensolarado e os solos pedregosos da região com aromas intensos de morango maduro, figo, couro e as clássicas ervas selvagens (garrigue) do Mediterrâneo. Um vinho encorpado, quente e generoso, feito sob medida para acompanhar ensopados ricos e carnes assadas lentamente. Perfeito! Vamos finalizar a página 2 de Bebidas Importadas com as descrições detalhadas dos produtos 57 a 72. Aqui estão as descrições comerciais para o documento:"
    },
    { "id": 67, "title": "Vinho M. Chapoutier Les Meysonniers 2020 750ml", "price": "603,54", "category": "Bebidas", "details": "750ml", "image_url": "https://corkscrewcellars.com.au/wp-content/uploads/2019/10/M-Chapoutier-Crozes-Hermitage-Les-Meysonniers-Rouge.webp",
        "description": "Uma safra espetacular para a Syrah francesa orgânica. Seus aromas intensos de amoras maduras, violeta e um toque marcante de pimenta preta envolvem o paladar com uma estrutura elegante, redonda e carnuda. Um tinto que brilha na mesa, acompanhando perfeitamente churrascos premium e carnes ricas."
    },
    { "id": 68, "title": "Vinho Cobos Bramare Valle de Uco 2022 750ml", "price": "385,08", "category": "Bebidas", "details": "750ml", "image_url": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m5khx9i8aqts66",
        "description": "A elite do Malbec argentino assinada pelo renomado enólogo Paul Hobbs. O Bramare Valle de Uco (750ml) captura a essência dos vinhedos de altitude. É um tinto de cor profunda, com aromas exuberantes de violeta, cassis e notas elegantes de chocolate. Potente, aveludado e com final persistente, é um ícone para grandes momentos."
    },
    { "id": 69, "title": "Vinho Taylor's Select Reserve Port 750ml", "price": "373,46", "category": "Bebidas", "details": "750ml", "image_url": "https://revistaadega.uol.com.br/media/_versions/garrafas/taylors_select_reserve_port_sm.jpg",
        "description": "A introdução perfeita ao mundo dos Vinhos do Porto. O Taylor's Select Reserve (750ml) é focado na exuberância e na juventude da fruta. Com aromas vigorosos de frutas negras maduras e um paladar encorpado e suculento, é versátil e ideal para acompanhar tábuas de queijos ou sobremesas à base de chocolate escuro."
    },
    { "id": 70, "title": "Vinho Taylor's Late Bottled Vintage 2019 750ml", "price": "257,28", "category": "Bebidas", "details": "750ml", "image_url": "https://cellshop.com/media/catalog/product/4/8/4809708_1_f977_1.jpg?optimize=medium&amp;bg-color=255,255,255&amp;fit=bounds&amp;height=265&amp;width=265&amp;canvas=265:265",
        "description": "O pioneirismo da Taylor's em uma garrafa de excelência. O Late Bottled Vintage (LBV) 2019 (750ml) oferece a riqueza de um Porto Vintage, mas já pronto para beber. Revela aromas profundos de cereja preta, ameixa e especiarias. Encorpado e estruturado, é o parceiro ideal para queijos azuis."
    },
    { "id": 71, "title": "Vinho Taylor's 10 Year Old Tawny Port 750ml", "price": "373,46", "category": "Bebidas", "details": "750ml", "image_url": "https://adegabarrels.com.br/wp-content/uploads/2025/07/4809722_1_6666_1.png",
        "description": "A elegância do tempo em uma taça. Envelhecido lentamente em barris de carvalho, este Tawny de 10 anos adquire uma cor âmbar e um perfil sedutor de caramelo, mel, nozes e madeira tostada. No paladar, é incrivelmente macio e aveludado. Perfeito para acompanhar sobremesas com amêndoas."
    },
    { "id": 72, "title": "Vinho Errazuriz The Blend Collection 2020 750ml", "price": "580,31", "category": "Bebidas", "details": "750ml", "image_url": "https://www.bebidaonline.com.br/media/catalog/product/cache/1/thumbnail/800x/99cfa2db909aa8be0aba7059fa3f7550/v/i/vinho_errazuriz_the_blend_collection_red_750ml_-_2020.png",
        "description": "Uma obra-prima da viticultura chilena. O Errazuriz The Blend (750ml) é um corte magistral de uvas tintas clássicas do Vale do Aconcágua. Expressa camadas de cassis, amoras, tabaco e especiarias doces. Com taninos firmes e maduros, é estruturado para brilhar ao lado de carnes grelhadas e pratos intensos."
    },
    { "id": 73, "title": "Vinho Errazuriz Max Cabernet 2021 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://i.zst.com.br/thumbs/12/8/36/1969622336.jpg" },
    { "id": 74, "title": "Vinho Errazuriz Max Merlot 2021 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://www.grandcru.com.br/media/catalog/product/cache/8d08538132235aee2ff50a612624b1c3/c/h/cherr0304a15.png" },
    { "id": 75, "title": "Vinho Errazuriz Max Syrah 2021 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://ciadovinho.cdn.magazord.com.br/img/2024/03/produto/5188/3.jpg" },
    { "id": 76, "title": "Vinho Errazuriz Max Carmenere 2021 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://naturalterra.vtexassets.com/arquivos/ids/169080/Vinho-Tinto-Errazuriz-1870-Carmenere-750ml.jpg?v=638671094409070000" },
    { "id": 77, "title": "Vinho Errazuriz Max Chardonnay 2022 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://www.vinhosmundi.com.br/image/cache/catalog/Chile/Grand Cru/Errazuriz/Errazuriz Reserva Chardonnay-1200x1200.PNG" },
    { "id": 78, "title": "Vinho Errazuriz Max Pinot Noir 2022 750ml", "price": "154,17", "category": "Bebidas", "details": "750ml", "image_url": "https://images.tcdn.com.br/img/img_prod/1114520/vinho_errazuriz_estate_reserva_pinot_noir_750ml_2022_13145_1_579485c7dc9c73ddf4c1f5a5a685673f.jpg" },
    { "id": 79, "title": "Errazuriz Max Red Blend 2021 375ml", "price": "84,32", "category": "Bebidas", "details": "375ml", "image_url": "https://centergourmet.com.br/wp-content/uploads/2024/05/Errazuriz-Max-VIII-Blend-2019-Degustando.jpg" },
    { "id": 80, "title": "Vinho Montes Alpha Cabernet 2021 750ml", "price": "194,17", "category": "Bebidas", "details": "750ml", "image_url": "https://casavinhos.com.br/media/catalog/product/cache/2/image/9df78eab33525d08d6e5fb8d27136e95/v/i/vinho-montes-alpha-cabernet-sauvignon-2020-2407310313.png" },
    { "id": 81, "title": "Vinho Montes Alpha Merlot 2021 750ml", "price": "194,17", "category": "Bebidas", "details": "750ml", "image_url": "https://hortifrutibr.vtexassets.com/arquivos/ids/175410/montes-merlot_600x800+fill_ffffff -1-.jpg?v=638887191462970000" },
    { "id": 82, "title": "Vinho Montes Alpha Syrah 2021 750ml", "price": "194,17", "category": "Bebidas", "details": "750ml", "image_url": "https://cdn.awsli.com.br/2500x2500/1868/1868919/produto/230466433/vinho-montes-alpha-syrah-c08ir051c2.png" },
    { "id": 84, "title": "Vinho Montes Alpha Chardonnay 2022 750ml", "price": "194,17", "category": "Bebidas", "details": "750ml", "image_url": "https://cdn.dooca.store/4466/products/7m9uvrocxmbxo0sc3vyuhbkymqd3wu5wmvaw_640x640+fill_ffffff.png?v=1691710064&amp;webp=0" },
    { "id": 85, "title": "Vinho Montes Purple Angel 2020 750ml", "price": "1.941,74", "category": "Bebidas", "details": "750ml", "image_url": "https://mambodelivery.vtexassets.com/arquivos/ids/205342/278861-Vinho-Chileno-Montes-Purple-Angel-Carmenere-750ml.jpg?v=638422445969970000" },
    { "id": 86, "title": "Vinho Almaviva 2020 750ml", "price": "3.883,48", "category": "Bebidas", "details": "750ml", "image_url": "https://images.tcdn.com.br/img/img_prod/1268793/almaviva_2020_48883_1_e180b0afc109cfa26a9582f067588382.jpg" },
    // PERFUMARIA
    { "id": 87, "title": "Perfume Carolina Herrera Good Girl EDP 80ml", "price": "684,36", "category": "Perfumaria", "details": "Feminino", "image_url": "https://promoon.com.br/wp-content/uploads/2023/11/399304272_1372860026642070_4993223919599671513_n.jpg" },
    { "id": 88, "title": "Perfume Paco Rabanne 1 Million EDT 100ml", "price": "560,93", "category": "Perfumaria", "details": "Masculino", "image_url": "https://static.wixstatic.com/media/8bdc36_b031d70e7a02437f8a795a614b29ec70~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg" },
    { "id": 89, "title": "Perfume Lancôme La Vie Est Belle EDP 100ml", "price": "732,84", "category": "Perfumaria", "details": "Feminino", "image_url": "https://cdn.dooca.store/3359/products/wpdv7jrhn8yj4ymb11mgf8oguyibo65c3xm2.png?v=1680577421" },
    { "id": 90, "title": "Perfume Giorgio Armani Sì EDP 100ml", "price": "740,00", "category": "Perfumaria", "details": "Feminino", "image_url": "https://nissei.com/media/catalog/product/cache/16a9529cefd63504739dab4fc3414065/p/e/perfume_giorgio_armani_s_edp_-_femenino_50ml.jpg" },
    { "id": 91, "title": "Perfume Paco Rabanne Invictus EDT 100ml", "price": "533,02", "category": "Perfumaria", "details": "Masculino", "image_url": "https://cdn.awsli.com.br/2500x2500/2432/2432464/produto/167667807/5e01c9bd0a.jpg" },
    { "id": 92, "title": "Perfume Hugo Boss Iced EDT 75ml", "price": "380,00", "category": "Perfumaria", "details": "Masculino", "image_url": "https://carrefourbr.vtexassets.com/arquivos/ids/137951730/a9eab2fb44f94da2bfe64928ca03d1a1.jpg?v=638441381921630000" },
    { "id": 93, "title": "Perfume Calvin Klein Eternity for Men 100ml", "price": "412,00", "category": "Perfumaria", "details": "Masculino", "image_url": "https://calvinklein.vtexassets.com/arquivos/ids/552743/25198-0_2.jpg?v=637649236871900000" },
    { "id": 94, "title": "Vinho Torbreck Cuvée Juveniles 2022 750ml", "price": "373,46", "category": "Bebidas", "details": "750ml", "image_url": "https://corkscrewcellars.com.au/wp-content/uploads/2021/04/Torbreck-Cuvee-Juveniles.webp",
        "description": "A expressão pura do Barossa Valley na Austrália. O Torbreck Cuvée Juveniles (750ml) é um tinto vibrante inspirado nos cortes do Vale do Rhône (Grenache, Mataro e Shiraz), criado sem passagem por carvalho para destacar a fruta fresca e a vivacidade. Com notas intensas de frutas vermelhas escuras, especiarias e um final sedoso, é um vinho extremamente gastronômico, perfeito para acompanhar pratos mediterrâneos e carnes grelhadas."
    },
    { "id": 95, "title": "Vinho La Fiole Du Pape Châteauneuf-Du-Pape 750 ML", "price": "580,31", "category": "Bebidas", "details": "750 ML", "image_url": "https://images.tcdn.com.br/img/img_prod/686223/vinho_tinto_la_fiole_du_pape_chateauneuf_du_pape_750ml_33990594_1_70ad5e284b18b07d29d2c59068959248.png",
        "description": "Um ícone mundialmente reconhecido pela sua clássica garrafa retorcida. O La Fiole Du Pape (750ml) é um autêntico Châteauneuf-du-Pape francês, elaborado a partir de um corte de múltiplas safras para garantir consistência e maturidade. Repleto de notas de frutas secas, especiarias, alcaçuz e figo, possui um paladar rico, maduro e envolvente. Uma joia do Vale do Rhône para harmonizar com pratos intensos e presentear colecionadores."
    },
    { "id": 96, "title": "Licor Caffo Vecchio Amaro del Capo - 750mL", "price": "218,68", "category": "Bebidas", "details": "750mL", "image_url": "https://estadoliquido.pt/12772-large_default/licor-vecchio-amaro-del-capo.jpg",
        "description": "O amaro mais amado da Itália. O Vecchio Amaro del Capo da Caffo (750ml) é um licor de ervas da Calábria, destilado segundo uma receita secular que combina 29 ervas, flores, frutas e raízes. Com sabor doce-amargo perfeitamente equilibrado e notas vibrantes de flor de laranjeira, camomila e menta, a tradição dita que deve ser servido estupidamente gelado (ideal a -20°C) em pequenos cálices como digestivo após as refeições."
    },
    { "id": 97, "title": "Licor Tequila Rose Strawberry Cream 1LT", "price": "255,99", "category": "Bebidas", "details": "1LT", "image_url": "https://static.wixstatic.com/media/8bdc36_f0fd8c94efc447abb46b58f2719aa819~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
        "description": "Ousadia e doçura em uma garrafa irresistível. O Tequila Rose (1 Litro) revolucionou o mercado ao combinar um rico e aveludado creme de morango com um toque ousado de tequila mexicana premium. Com sua cor rosa vibrante e sabor surpreendentemente suave que lembra um milkshake alcoólico de morango, é a escolha perfeita para ser consumido em shots gelados, em drinks criativos ou servido sobre sobremesas."
    },
    { "id": 98, "title": "Vinho Vik La Piu Belle Rosé 2022 750ml", "price": "260,60", "category": "Bebidas", "details": "750ml", "image_url": "https://images.yampi.me/assets/stores/click-multishop-ecommerce/uploads/images/vinho-vik-la-piu-belle-rose-2022-750ml-686da821ec7ee-large.png",
        "description": "A obra de arte engarrafada que celebra a beleza da vida. O La Piu Belle da Viña VIK (750ml) é muito mais do que a sua garrafa visualmente deslumbrante. Este blend chileno exibe uma precisão cirúrgica de Cabernet Sauvignon, Carménère e Syrah. No nariz, é uma explosão de frutas negras maduras, cassis, especiarias doces e toques florais delicados. É um vinho voluptuoso, sedoso, com taninos finos e um final vibrante. Um tinto moderno, luxuoso e inesquecível."
    },
    { "id": 99, "title": "Vinho Catena Alta Malbec 2019 750ml", "price": "486,00", "category": "Bebidas", "details": "750ml", "image_url": "https://i.zst.com.br/thumbs/12/16/e/-27790118.jpg",
        "description": "Um marco na história do vinho sul-americano. Elaborado a partir da seleção criteriosa de fileiras históricas da Catena Zapata. Elegante, oferece aromas minerais, florais e de frutas negras puras. Na boca é denso, fresco e com taninos sedosos. O auge da elegância do Malbec mendocino."
    },
    { "id": 100, "title": "Gin Hendrick's Grand Cabaret - 700ML", "price": "367,24", "category": "Bebidas", "details": "700ML", "image_url": "https://www.kroger.com/product/images/large/front/0008366410731",
        "description": "Uma edição limitada que é um espetáculo para os sentidos. Inspirado na tradição histórica de destilados europeus, esta versão extravagante traz a clássica infusão de pepino e rosa unida a uma sinfonia decadente de frutas de caroço e ervas doces. Perfeito para G&Ts luxuosos e para colecionadores."
    },
    { "id": 101, "title": "Whisky Gold Bar Rickhouse 750ML", "price": "495,04", "category": "Bebidas", "details": "750ML", "image_url": "https://www.bebidaonline.com.br/media/catalog/product/cache/1/thumbnail/800x/99cfa2db909aa8be0aba7059fa3f7550/w/h/whisky_gold_bar_rickhouse_750ml_2.jpg",
        "description": "A expressão mais ousada e robusta do ouro líquido. O Gold Bar Bourbon Black (750ml) é um autêntico bourbon americano, amadurecido duplamente para extrair o máximo de cor e complexidade da madeira. Revela um perfil aromático denso de fumaça doce, chocolate amargo, mel e carvalho tostado. Excepcional para ser degustado puro (\"neat\") ou com uma única pedra de gelo."
    },
    { "id": 102, "title": "Tequila Reposado Patrón 750 ML", "price": "540,16", "category": "Bebidas", "details": "750 ML", "image_url": "https://124866021.cdn6.editmysite.com/uploads/1/2/4/8/124866021/s751106300478995959_p176_i1_w1500.jpeg",
        "description": "A perfeição artesanal mexicana com um leve toque de madeira. A Tequila Patrón Reposado (750ml) repousa em barris de carvalho por pelo menos dois meses. Esse tempo é suficiente para arredondar a bebida, adicionando notas sutis de baunilha, mel e carvalho ao frescor cítrico e marcante da agave azul de Jalisco. É a escolha ideal para quem busca uma tequila de degustação suave ou margaritas ultrapremium."
    },
    { "id": 103, "title": "Vinho Tenuta San Guido Sassicaia 2020 750ml", "price": "3.500,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.bebidaonline.com.br/media/catalog/product/cache/1/thumbnail/800x/99cfa2db909aa8be0aba7059fa3f7550/v/i/vinho_tenuta_san_guido_sassicaia_750ml.jpg" },
    { "id": 104, "title": "Vinho Marchesi Antinori Tignanello 2020 750ml", "price": "1.850,00", "category": "Bebidas", "details": "750ml", "image_url": "https://http2.mlstatic.com/D_NQ_NP_835393-MLU74870358966_032024-O.webp" },
    { "id": 105, "title": "Vinho Dal Forno Romano Amarone 2015 750ml", "price": "3.800,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.bancadoramon.com.br/media/catalog/product/v/i/vinho-amarone-della-dal-forno-roman.jpg" },
    { "id": 106, "title": "Vinho Penfolds Grange Bin 95 Shiraz 2018 750ml", "price": "6.500,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.bancadoramon.com.br/media/catalog/product/cache/1/thumbnail/1580x/9df78eab33525d08d6e5fb8d27136e95/v/i/vinho_penfolds_grange.png" },
    { "id": 107, "title": "Whisky Johnnie Walker Blue Label 750ml", "price": "1.250,00", "category": "Bebidas", "details": "750ml", "image_url": "https://images.tcdn.com.br/img/img_prod/947695/whisky_johnnie_walker_blue_label_750ml_687_2_96696eb2e123a01df4eee15a83b20000.jpg" },
    { "id": 108, "title": "Whisky Macallan 12 Years Old Double Cask 700ml", "price": "680,00", "category": "Bebidas", "details": "700ml", "image_url": "https://images.tcdn.com.br/img/img_prod/584699/whisky_the_macallan_double_cask_12_anos_700ml_5753_1_2dec1716e74e622b96f92e5026f7d314.jpeg" },
    { "id": 109, "title": "Whisky Chivas Regal 18 Years 750ml", "price": "450,00", "category": "Bebidas", "details": "750ml", "image_url": "https://covabra.vtexassets.com/arquivos/ids/214736/38255.jpg?v=638306433769530000" },
    { "id": 110, "title": "Gin Hendrick's 750ml", "price": "280,00", "category": "Bebidas", "details": "750ml", "image_url": "https://images.tcdn.com.br/img/img_prod/584699/gin_hendrick_s_750ml_210_1_20171004153919.jpg" },
    { "id": 111, "title": "Gin Tanqueray No. Ten 700ml", "price": "240,00", "category": "Bebidas", "details": "700ml", "image_url": "https://emporiomilao.com.br/wp-content/uploads/2024/10/Tanqueray-No.-Ten-Gin-0.75L.png" },
    { "id": 112, "title": "Licor Amarula Cream 750ml", "price": "115,00", "category": "Bebidas", "details": "750ml", "image_url": "https://images.tcdn.com.br/img/img_prod/1303599/licor_amarula_cream_750_ml_543_2_b8e13ade686748d16ceb6cbe3bfa633b.jpg" },
    { "id": 113, "title": "Licor Cointreau 700ml", "price": "165,00", "category": "Bebidas", "details": "700ml", "image_url": "https://americanas.vtexassets.com/arquivos/ids/446630/7302989723_1_xlarge.jpg?v=638750824501600000" },
    { "id": 114, "title": "Champagne Moët & Chandon Brut Imperial 750ml", "price": "480,00", "category": "Bebidas", "details": "750ml", "image_url": "https://static.wixstatic.com/media/6a24b0_aa2e752e9e7148c9ae4d881135b090c3~mv2.jpg/v1/fill/w_980,h_980,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/6a24b0_aa2e752e9e7148c9ae4d881135b090c3~mv2.jpg" },
    { "id": 115, "title": "Champagne Veuve Clicquot Yellow Label 750ml", "price": "520,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.rodeoclub.com.br/wp-content/uploads/2024/04/champagne-veuve-clicquot-brut-750ml_1.jpg" },
    { "id": 116, "title": "Alfajor Havanna Chocolate 70% Cacau (6 un)", "price": "98,00", "category": "Delicatessen", "details": "300g", "image_url": "https://d2w1em06bjazhl.cloudfront.net/Custom/Content/Themes/Shared/Havanna/logo.webp" },
    { "id": 117, "title": "Alfajor Havanna Nuez (6 un)", "price": "105,00", "category": "Delicatessen", "details": "300g", "image_url": "https://vdeveganca.s3.amazonaws.com/product/image/1487/front_pt.3.full.jpg" },
    { "id": 118, "title": "Doce de Leite Havanna Tradicional 450g", "price": "65,00", "category": "Delicatessen", "details": "450g", "image_url": "https://obahortifruti.vtexassets.com/arquivos/ids/4265973/Doce-De-Leite-Havanna-420-G.jpg?v=638144123594400000" },
    { "id": 119, "title": "Doce de Leite Havanna Tradicional 850g", "price": "110,00", "category": "Delicatessen", "details": "850g", "image_url": "https://obahortifruti.vtexassets.com/arquivos/ids/4265973/Doce-De-Leite-Havanna-420-G.jpg?v=638144123594400000" },
    { "id": 120, "title": "Chocolate Lindt Excellence 70% Cocoa 100g", "price": "32,00", "category": "Delicatessen", "details": "100g", "image_url": "https://covabra.vtexassets.com/arquivos/ids/212072/3046920028004.3.jpg?v=638277871613570000" },
    { "id": 121, "title": "Chocolate Lindt Excellence Sea Salt 100g", "price": "32,00", "category": "Delicatessen", "details": "100g", "image_url": "https://covabra.vtexassets.com/arquivos/ids/212504/4000539045080.2.jpg?v=638283239203700000" },
    { "id": 122, "title": "Chocolate Toblerone Milk 100g", "price": "18,50", "category": "Delicatessen", "details": "100g", "image_url": "https://images.tcdn.com.br/img/img_prod/1176430/180_toblerone_milk_100g_3219_1_e401ed7420b0e8160d00a78abe692fbc.png" },
    { "id": 123, "title": "Chocolate Toblerone Dark 100g", "price": "18,50", "category": "Delicatessen", "details": "100g", "image_url": "https://www.eastereggwarehouse.com.au/wp-content/uploads/2022/10/Toblerone-Dark-Chocolate-100g.jpg" },
    { "id": 124, "title": "Perfume Dior Sauvage EDT 100ml", "price": "650,00", "category": "Perfumaria", "details": "Masculino", "image_url": "https://carrefourbr.vtexassets.com/arquivos/ids/179405938/perfume-masculino-dior-sauvage-edt-60-ml.jpg?v=638675359104800000" },
    { "id": 125, "title": "Perfume Chanel No. 5 EDP 100ml", "price": "890,00", "category": "Perfumaria", "details": "Feminino", "image_url": "https://carrefourbr.vtexassets.com/arquivos/ids/135034205/85bc16e389474b4b9d46e672a835b364.jpg?v=638371156041270000" },
    { "id": 126, "title": "Perfume Bleau de Chanel EDP 100ml", "price": "780,00", "category": "Perfumaria", "details": "Masculino", "image_url": "https://images-americanas.b2w.io/produtos/4993669517/imagens/perfume-bleu-de-chanel-100ml-edp-masculino/4993669517_1_xlarge.jpg" },
    { "id": 127, "title": "Perfume Lancôme Idôle EDP 75ml", "price": "560,00", "category": "Perfumaria", "details": "Feminino", "image_url": "https://www.ofertinha.com.br/wp-content/uploads/2024/05/perfff.png" },
    { "id": 128, "title": "Vinho Catena Zapata Malbec Argentino 750ml", "price": "980,00", "category": "Bebidas", "details": "750ml", "image_url": "https://obahortifruti.vtexassets.com/arquivos/ids/11473822/Vinho-Argentino-Catena-Zapata-Malbec-Pylloxera-750ml.png?v=638835320931800000" },
    { "id": 129, "title": "Vinho El Enemigo Malbec 750ml", "price": "285,00", "category": "Bebidas", "details": "750ml", "image_url": "https://cdn.dooca.store/4466/products/png-20211128-195749-0000_640x640+fill_ffffff.png?v=1638143360&amp;webp=0" },
    { "id": 130, "title": "Vinho Angelica Zapata Malbec Alta 750ml", "price": "420,00", "category": "Bebidas", "details": "750ml", "image_url": "https://cdn.awsli.com.br/2500x2500/2642/2642813/produto/233384046/876004bf3bdc601b22e9a687cd2dc878-uqa4rsr2rh.jpg" },
    { "id": 131, "title": "Azeite De Oliva Colinas De Garzón 500ml", "price": "125,00", "category": "Delicatessen", "details": "500ml", "image_url": "https://images.tcdn.com.br/img/img_prod/712359/azeite_de_oliva_extra_virgem_colinas_de_garzn_bi_1_20250919084626_8d142b12a90b.jpg" },
    { "id": 132, "title": "Azeite De Oliva O-Live & Co 500ml", "price": "85,00", "category": "Delicatessen", "details": "500ml", "image_url": "https://bompreco.vtexassets.com/arquivos/ids/155483/AzeitedeOlivaExtraVirgemChilenoOLiveCo500ml.jpg?v=637460617019830000" },
    { "id": 133, "title": "Biscoito Lotus Biscoff XL 750g", "price": "145,00", "category": "Delicatessen", "details": "750g", "image_url": "https://supernossoio.vtexassets.com/arquivos/ids/292564/224814.png?v=638515693993930000" },
    { "id": 134, "title": "Chocolate Milka Bubbly Milk 100g", "price": "16,50", "category": "Delicatessen", "details": "100g", "image_url": "https://supernossoio.vtexassets.com/arquivos/ids/468085/173442_2.png?v=638595107885030000" },
    { "id": 135, "title": "Chocolate Milka Strawberry Cheesecake 300g", "price": "42,00", "category": "Delicatessen", "details": "300g", "image_url": "https://mambodelivery.vtexassets.com/arquivos/ids/224710/produto_ecommerce294407_11621.jpg?v=638689071138230000" },
    { "id": 136, "title": "Vinho Pera Manca Tinto 2015 750ml", "price": "4.500,00", "category": "Bebidas", "details": "750ml", "image_url": "https://boa.vtexassets.com/arquivos/ids/533307/Vinho-Tinto-Pera-Manca-750ml.jpg?v=638478432103670000" },
    { "id": 137, "title": "Vinho Barca Velha 2011 750ml", "price": "7.800,00", "category": "Bebidas", "details": "750ml", "image_url": "https://casalisboa.com.br/wp-content/uploads/2022/09/Vinho-Barca-Velha-2011-750Ml.jpg" },
    { "id": 138, "title": "Vinho Chateau Petrus 2017 750ml", "price": "35.000,00", "category": "Bebidas", "details": "750ml", "image_url": "https://www.bancadoramon.com.br/media/catalog/product/p/e/petrus_97.jpg" },
    { "id": 139, "title": "Vinho Opus One 2018 750ml", "price": "6.200,00", "category": "Bebidas", "details": "750ml", "image_url": "https://static.wixstatic.com/media/f92c30_225ab2de87fe4099a25683af8bcc0539~mv2.png/v1/fit/w_500,h_500,q_90/file.png" },
    { "id": 140, "title": "Perfume Paco Rabanne Lady Million EDP 80ml", "price": "540,00", "category": "Perfumaria", "details": "Feminino", "image_url": "https://acdn.mitiendanube.com/stores/003/246/709/products/5875b5f2b7714feb275523e3a6f362421-d6e7fee72ae9e9ce7a16884384872313-640-0.jpg" }

];
